### ISSUE TITLE
nan issue and a typo?

### ISSUE THREAD

**Issue by chentingpc** [Bonnevie/rebar#1]
Hi, 

Thanks for sharing the code. Just wondering the reason of using killnan() function? It seems you have eps for all tf.log, so I am not sure where nan can arise..

Also, in this [line](https://github.com/Bonnevie/rebar/blob/2f526300eed123af64f6df601fdfaea3f5fd6dd5/relaxflow/reparam.py#L76), shouldn't self.b be self.zb?

**Comment by Bonnevie** [comment]
@chentingpc sorry for the late answer! Holiday period has been keeping me. And yes, that is an awful typo... I'll fix that immediately.

The NaN issue is a bit obscure, which is also why I made it a switchable feature. Running the experiments (10000 gradient computations for each type of estimator), I'd get an error from one of the boxplot commands. It would always be one of the binary cases (optimized+coupled seems to be a slightly more frequent offender), and inspecting the arrays a *single* value of the entire (10000,20,10) array (runs x params) would be NaN. My hypothesis is that it is an under- or overflow problem for a particularly malevolent sample, but it's hard to isolate and seemed to happen so infrequently that I doubt there is great harm in killing it. The categorical setting never has problems.
  
edit: should be fixed in the main branch now.
